### PR TITLE
Callback and Shifty update

### PR DESCRIPTION
**Pull request by jeremyckahn**
I updated Shifty to 0.4.1.  Sorry I didn't do this in my other PR, but I've been working on both projects in tandem and it kinda got caught up in an older commit.

More importantly, I added a callback option.  Works as you'd expect, and it is demonstrated in `demo.html`.  I also updated the README to reflect the change.

### CODE REVIEW

**Comment by joelambert** [comment]
Thanks for the update! I'll take a proper look into this on Monday morning.

I'm in two minds about the `callback` functions, I guess it's a useful addition but it does duplicate the the functionality of listening for the `webkitTransitionEnd` event? Can you give a use case where the callback is better than listening for the event?

**Comment by jeremyckahn** [comment]
My addition listens for the event, what I've added is really just a convenience for users of Morf.  `animationEndListener` gets called with every invokation of `Morf()`, so having a handler bound to "webkitTransitionEnd" is guaranteed.  Having a `callback` option, called in Morf's event handler, would allow  user to inject functionality into `Morf` calls without having to bind more event handlers, thus saving on memory.  To me, this just seems like a "might as well" situation - if this functionality isn't in Morf, I imagine people are going to wonder why it isn't, since callbacks are such a normal part of JavaScript development - particularly with animation.

**Comment by joelambert** [comment]
You make a good case. Originally morf was designed as a shim to make transitions appear to work with with custom easing functions.

I suspect however, as you hint at, most people don't care too much about that and just see this as a lightweight mobile friendly animation lib. So I think you're right and we should add the callback! 

Just to play devils advocate, is 'callback' the best name? jQuery uses 'complete' and Scriptaculous uses 'afterFinish', I think 'callback' is probably fine?

**Comment by jeremyckahn** [comment]
Yay!

I'm not sure about the name.  I'm open to whatever ideas you propose on that.  To me, "callback" is more easily recognized as a construct in async programming, but I'm not married to it.  I tend to stay from using "complete" as callback names, if only to differentiate from jQuery.

**Comment by joelambert** [comment]
Merged your changes and also added some code to trigger the `callback` when the transition is a natively supported function ([see details](https://github.com/joelambert/morf/blob/master/js/src/morf.js#L102)).

**Comment by jeremyckahn** [comment]
Ahhh, I see.  I didn't see that part of the code.  Nice!

**Pull request merged**
